import mouseSingleOne from '../assets/images/hero-mouse-single-1.png';
import mouseSingleTwo from '../assets/images/hero-mouse-single-2.png';
import './HeroFloatingMice.css';

const FLOATING_MICE = [
  {
    id: 'float-mouse-1',
    image: mouseSingleOne,
    left: '44%',
    size: '9rem',
    driftX: '5.5rem',
    duration: '40s',
    delay: '0s',
    swayDuration: '6.8s',
    swayDelay: '-1.4s',
    rotation: '-11deg',
    rotationDrift: '6deg',
    spinTurn: '132deg',
    spinDuration: '14.5s',
    spinDelay: '-2.5s',
    blur: '5.5px',
    opacity: 0.82,
    layer: 0,
  },
  {
    id: 'float-mouse-3',
    image: mouseSingleOne,
    left: '55%',
    size: '24rem',
    driftX: '1rem',
    duration: '24s',
    delay: '-4s',
    swayDuration: '7.4s',
    swayDelay: '-0.9s',
    rotation: '-10deg',
    rotationDrift: '5deg',
    spinTurn: '364deg',
    spinDuration: '17.8s',
    spinDelay: '-10.2s',
    blur: '0px',
    opacity: 1,
    layer: 2,
    isForeground: true,
  },
  {
    id: 'float-mouse-4',
    image: mouseSingleTwo,
    left: '75%',
    size: '21rem',
    driftX: '-1.25rem',
    duration: '24s',
    delay: '-12s',
    swayDuration: '8.1s',
    swayDelay: '-2.8s',
    rotation: '-16deg',
    rotationDrift: '6.5deg',
    spinTurn: '-94deg',
    spinDuration: '13.2s',
    spinDelay: '-4.1s',
    blur: '0px',
    opacity: 1,
    layer: 2,
    isForeground: true,
  },
  {
    id: 'float-mouse-5',
    image: mouseSingleOne,
    left: '90%',
    size: '14rem',
    driftX: '4.75rem',
    duration: '21s',
    delay: '-3.5s',
    swayDuration: '6.2s',
    swayDelay: '-3.3s',
    rotation: '-12deg',
    rotationDrift: '5.5deg',
    spinTurn: '208deg',
    spinDuration: '15.4s',
    spinDelay: '-12.8s',
    blur: '2.6px',
    opacity: 0.86,
    layer: 1,
  },
  {
    id: 'float-mouse-6',
    image: mouseSingleTwo,
    left: '48%',
    size: '13rem',
    driftX: '-3.25rem',
    duration: '21s',
    delay: '-10.5s',
    swayDuration: '7.8s',
    swayDelay: '-4.1s',
    rotation: '-18deg',
    rotationDrift: '5deg',
    spinTurn: '-146deg',
    spinDuration: '18s',
    spinDelay: '-9s',
    blur: '2.4px',
    opacity: 0.82,
    layer: 1,
  },
  {
    id: 'float-mouse-7',
    image: mouseSingleOne,
    left: '74%',
    size: '8.25rem',
    driftX: '6rem',
    duration: '40s',
    delay: '-3.3s',
    swayDuration: '8.6s',
    swayDelay: '-1.8s',
    rotation: '-9deg',
    rotationDrift: '6.25deg',
    spinTurn: '172deg',
    spinDuration: '19.5s',
    spinDelay: '-5.8s',
    blur: '6.2px',
    opacity: 0.72,
    layer: 0,
  },
  {
    id: 'float-mouse-8',
    image: mouseSingleTwo,
    left: '96%',
    size: '7rem',
    driftX: '-7.25rem',
    duration: '40s',
    delay: '-6.6s',
    swayDuration: '7.1s',
    swayDelay: '-3.6s',
    rotation: '-21deg',
    rotationDrift: '4.75deg',
    spinTurn: '-118deg',
    spinDuration: '16.7s',
    spinDelay: '-7.4s',
    blur: '6.6px',
    opacity: 0.7,
    layer: 0,
  },
  {
    id: 'float-mouse-9',
    image: mouseSingleOne,
    left: '93%',
    size: '20rem',
    driftX: '-1.5rem',
    duration: '24s',
    delay: '-20s',
    swayDuration: '7.2s',
    swayDelay: '-2.6s',
    rotation: '-12deg',
    rotationDrift: '5.25deg',
    spinTurn: '246deg',
    spinDuration: '15.8s',
    spinDelay: '-8.4s',
    blur: '0px',
    opacity: 1,
    layer: 2,
    isForeground: true,
  },
  {
    id: 'float-mouse-10',
    image: mouseSingleTwo,
    left: '88%',
    size: '12.75rem',
    driftX: '-4.5rem',
    duration: '21s',
    delay: '-17.5s',
    swayDuration: '8.9s',
    swayDelay: '-4.8s',
    rotation: '-15deg',
    rotationDrift: '5.75deg',
    spinTurn: '-162deg',
    spinDuration: '18.4s',
    spinDelay: '-11.2s',
    blur: '2.8px',
    opacity: 0.82,
    layer: 1,
  },
  {
    id: 'float-mouse-11',
    image: mouseSingleOne,
    left: '52%',
    size: '8rem',
    driftX: '3.75rem',
    duration: '40s',
    delay: '-10s',
    swayDuration: '8.2s',
    swayDelay: '-5.4s',
    rotation: '-13deg',
    rotationDrift: '5.2deg',
    spinTurn: '128deg',
    spinDuration: '20.5s',
    spinDelay: '-13.6s',
    blur: '6.1px',
    opacity: 0.68,
    layer: 0,
  },
  {
    id: 'float-mouse-12',
    image: mouseSingleTwo,
    left: '68%',
    size: '7.25rem',
    driftX: '-5.2rem',
    duration: '40s',
    delay: '-13.3s',
    swayDuration: '7.6s',
    swayDelay: '-2.9s',
    rotation: '-19deg',
    rotationDrift: '4.8deg',
    spinTurn: '-206deg',
    spinDuration: '17.2s',
    spinDelay: '-3.4s',
    blur: '6.8px',
    opacity: 0.66,
    layer: 0,
  },
  {
    id: 'float-mouse-13',
    image: mouseSingleOne,
    left: '98%',
    size: '8.4rem',
    driftX: '-8rem',
    duration: '40s',
    delay: '-16.6s',
    swayDuration: '9.4s',
    swayDelay: '-6.1s',
    rotation: '-8deg',
    rotationDrift: '6.4deg',
    spinTurn: '184deg',
    spinDuration: '21.6s',
    spinDelay: '-15.5s',
    blur: '6.4px',
    opacity: 0.7,
    layer: 0,
  },
  {
    id: 'float-mouse-14',
    image: mouseSingleTwo,
    left: '58%',
    size: '7.6rem',
    driftX: '4.2rem',
    duration: '40s',
    delay: '-20s',
    swayDuration: '8.4s',
    swayDelay: '-2.7s',
    rotation: '-17deg',
    rotationDrift: '5.4deg',
    spinTurn: '-142deg',
    spinDuration: '19.1s',
    spinDelay: '-6.2s',
    blur: '6.5px',
    opacity: 0.67,
    layer: 0,
  },
  {
    id: 'float-mouse-15',
    image: mouseSingleOne,
    left: '80%',
    size: '8.1rem',
    driftX: '-6.4rem',
    duration: '40s',
    delay: '-23.3s',
    swayDuration: '9.1s',
    swayDelay: '-3.9s',
    rotation: '-10deg',
    rotationDrift: '6.1deg',
    spinTurn: '218deg',
    spinDuration: '22.4s',
    spinDelay: '-9.6s',
    blur: '6.9px',
    opacity: 0.65,
    layer: 0,
  },
  {
    id: 'float-mouse-16',
    image: mouseSingleTwo,
    left: '92%',
    size: '7.4rem',
    driftX: '-3.8rem',
    duration: '40s',
    delay: '-26.6s',
    swayDuration: '7.9s',
    swayDelay: '-5.2s',
    rotation: '-22deg',
    rotationDrift: '4.9deg',
    spinTurn: '-188deg',
    spinDuration: '18.8s',
    spinDelay: '-12.8s',
    blur: '6.2px',
    opacity: 0.69,
    layer: 0,
  },
  {
    id: 'float-mouse-17',
    image: mouseSingleOne,
    left: '63%',
    size: '8.6rem',
    driftX: '5.6rem',
    duration: '40s',
    delay: '-30s',
    swayDuration: '8.7s',
    swayDelay: '-1.1s',
    rotation: '-14deg',
    rotationDrift: '5.8deg',
    spinTurn: '156deg',
    spinDuration: '20.8s',
    spinDelay: '-15.2s',
    blur: '6.7px',
    opacity: 0.66,
    layer: 0,
  },
  {
    id: 'float-mouse-18',
    image: mouseSingleTwo,
    left: '72%',
    size: '7.2rem',
    driftX: '-4.6rem',
    duration: '40s',
    delay: '-33.3s',
    swayDuration: '7.4s',
    swayDelay: '-4.4s',
    rotation: '-20deg',
    rotationDrift: '4.6deg',
    spinTurn: '-224deg',
    spinDuration: '17.9s',
    spinDelay: '-16.8s',
    blur: '7px',
    opacity: 0.64,
    layer: 0,
  },
  {
    id: 'float-mouse-19',
    image: mouseSingleOne,
    left: '86%',
    size: '8.3rem',
    driftX: '3.4rem',
    duration: '40s',
    delay: '-36.6s',
    swayDuration: '9.6s',
    swayDelay: '-6.5s',
    rotation: '-7deg',
    rotationDrift: '6.6deg',
    spinTurn: '196deg',
    spinDuration: '23s',
    spinDelay: '-18.5s',
    blur: '6.3px',
    opacity: 0.68,
    layer: 0,
  },
];

function HeroFloatingMice() {
  return (
    <div className="hero-floating-mice" aria-hidden="true">
      {FLOATING_MICE.map((mouse) => (
        <div
          key={mouse.id}
          className={`hero-floating-mice__item${
            mouse.isForeground ? ' hero-floating-mice__item--foreground' : ''
          }`}
          style={{
            '--mouse-left': mouse.left,
            '--mouse-size': mouse.size,
            '--mouse-drift-x': mouse.driftX,
            '--mouse-duration': mouse.duration,
            '--mouse-delay': mouse.delay,
            '--mouse-sway-duration': mouse.swayDuration,
            '--mouse-sway-delay': mouse.swayDelay,
            '--mouse-rotation': mouse.rotation,
            '--mouse-rotation-drift': mouse.rotationDrift,
            '--mouse-spin-turn': mouse.spinTurn,
            '--mouse-spin-duration': mouse.spinDuration,
            '--mouse-spin-delay': mouse.spinDelay,
            '--mouse-blur': mouse.blur,
            '--mouse-opacity': mouse.opacity,
            '--mouse-layer': mouse.layer,
          }}
        >
          <div className="hero-floating-mice__visual">
            <div className="hero-floating-mice__spin">
              {mouse.isForeground ? (
                <img
                  className="hero-floating-mice__image hero-floating-mice__image--fill"
                  src={mouse.image}
                  alt=""
                  draggable="false"
                />
              ) : null}
              <img
                className="hero-floating-mice__image"
                src={mouse.image}
                alt=""
                draggable="false"
              />
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

export default HeroFloatingMice;
